name: ecommerce
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg_provider: ^1.0.3
  flutter_lints: ^3.0.1
  intl: ^0.18.1
  page_transition: ^2.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Avenir
      fonts: 
        - asset: assets/fonts/AvenirMedium.ttf
          weight: 500
        - asset: assets/fonts/AvenirBlack.ttf
          weight: 900
        - asset: assets/fonts/AvenirHeavy.ttf
          weight: 800
        - asset: assets/fonts/AvenirRoman.ttf
          weight: 400
        - asset: assets/fonts/AvenirBook.ttf
          weight: 400
